spring.data.mongodb.uri=mongodb+srv://22130099:123@cluster0.i5kenr5.mongodb.net/mobile
# JWT Properties
app.jwt.secret=DayLaMotChuoiBiMatRatDaiVaAnToanHonRatNhieuSoVoiChuoiCuDeMaHoaJWTTokenCuaToi
app.jwt.expiration-ms=86400000